from __future__ import annotations

import json
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

import numpy as np

from .data import Array, Camera, Mesh, ReconstructionInput
from .io import load_mesh
from .nvdiffrec import (
    NvdiffrecRunConfig,
    copy_nvdiffrec_mesh,
    find_nvdiffrec_mesh,
    prepare_nvdiffrec_run,
)
from .visibility import update_visibility


class CoarseMeshGenerator(Protocol):
    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        ...


@dataclass
class ExistingMeshGenerator:
    mesh_path: Path | str
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        mesh = load_mesh(self.mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        return mesh


@dataclass
class ExternalCommandMeshGenerator:
    command: str
    output_mesh_path: Path | str
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        subprocess.run(shlex.split(self.command), check=True)
        mesh = load_mesh(self.output_mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        return mesh


@dataclass
class NvidiaInstantNGPMeshGenerator:
    """Adapter for NVIDIA Instant-NGP-style coarse mesh generation.

    The adapter writes a NeRF-style ``transforms.json`` from this package's
    cameras, calls a user-provided command template, then imports the mesh
    generated by that command. This keeps Instant-NGP as an interchangeable
    coarse backend instead of leaking it into refinement code.
    """

    scene_dir: Path | str
    output_mesh_path: Path | str
    command_template: str
    transforms_filename: str = "transforms.json"
    aabb_scale: int = 16
    convert_cv_to_gl: bool = True
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        if not images or not cameras:
            raise ValueError("Instant-NGP backend requires image paths and cameras.")
        scene_dir = Path(self.scene_dir)
        scene_dir.mkdir(parents=True, exist_ok=True)
        transforms_path = scene_dir / self.transforms_filename
        write_instant_ngp_transforms(
            transforms_path,
            images=images,
            cameras=cameras,
            scene_dir=scene_dir,
            aabb_scale=self.aabb_scale,
            convert_cv_to_gl=self.convert_cv_to_gl,
        )

        command = self.command_template.format(
            scene_dir=str(scene_dir),
            transforms_path=str(transforms_path),
            output_mesh_path=str(self.output_mesh_path),
        )
        subprocess.run(command, shell=True, check=True)

        mesh = load_mesh(self.output_mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        mesh.attributes["coarse_backend"] = "nvidia_instant_ngp"
        mesh.attributes["instant_ngp_transforms"] = str(transforms_path)
        return mesh


@dataclass
class NvidiaNvdiffrecMeshGenerator:
    """Adapter for using NVIDIA nvdiffrec as the coarse mesh generator."""

    run_dir: Path | str
    output_mesh_path: Path | str
    nvdiffrec_root: Path | str
    command_template: str = 'python train.py --config "{config_path}"'
    result_mesh_path: Path | str | None = None
    out_name: str = "coarse"
    run_config: NvdiffrecRunConfig | None = None
    convert_cv_to_gl: bool = True
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        if not images or not cameras:
            raise ValueError("nvdiffrec backend requires image paths and cameras.")
        data = ReconstructionInput(image_paths=images, cameras=cameras, mask_paths=None)
        prepared = prepare_nvdiffrec_run(
            data,
            run_dir=self.run_dir,
            out_name=self.out_name,
            config=self.run_config,
            convert_cv_to_gl=self.convert_cv_to_gl,
            masks=masks,
        )
        command = self.command_template.format(
            config_path=str(prepared.config_path),
            dataset_dir=str(prepared.nerf_dataset_dir),
            out_dir=str(prepared.nvdiffrec_out_dir),
            output_mesh_path=str(self.output_mesh_path),
            nvdiffrec_root=str(self.nvdiffrec_root),
        )
        subprocess.run(command, shell=True, check=True, cwd=self.nvdiffrec_root)
        result_mesh = find_nvdiffrec_mesh(prepared.nvdiffrec_out_dir, self.result_mesh_path)
        copy_nvdiffrec_mesh(result_mesh, self.output_mesh_path)
        mesh = load_mesh(self.output_mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        mesh.attributes["coarse_backend"] = "nvidia_nvdiffrec"
        mesh.attributes["nvdiffrec_config"] = str(prepared.config_path)
        mesh.attributes["nvdiffrec_output"] = str(prepared.nvdiffrec_out_dir)
        return mesh


def write_instant_ngp_transforms(
    path: Path | str,
    images: list[Path],
    cameras: list[Camera],
    scene_dir: Path | str,
    aabb_scale: int = 16,
    convert_cv_to_gl: bool = True,
) -> None:
    if len(images) != len(cameras):
        raise ValueError("Number of images and cameras must match.")
    scene_dir = Path(scene_dir)
    frames = []
    for image_path, camera in zip(images, cameras, strict=True):
        frames.append(
            {
                "file_path": _relative_image_path(image_path, scene_dir),
                "fl_x": float(camera.intrinsics[0, 0]),
                "fl_y": float(camera.intrinsics[1, 1]),
                "cx": float(camera.intrinsics[0, 2]),
                "cy": float(camera.intrinsics[1, 2]),
                "transform_matrix": camera_to_nerf_transform(
                    camera,
                    convert_cv_to_gl=convert_cv_to_gl,
                ).tolist(),
            }
        )

    first = cameras[0]
    payload = {
        "camera_model": "OPENCV",
        "fl_x": float(first.intrinsics[0, 0]),
        "fl_y": float(first.intrinsics[1, 1]),
        "cx": float(first.intrinsics[0, 2]),
        "cy": float(first.intrinsics[1, 2]),
        "w": int(first.image_size[0]) if first.image_size else None,
        "h": int(first.image_size[1]) if first.image_size else None,
        "aabb_scale": int(aabb_scale),
        "frames": frames,
    }
    if payload["w"] is None:
        del payload["w"]
        del payload["h"]

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def camera_to_nerf_transform(camera: Camera, convert_cv_to_gl: bool = True) -> Array:
    c2w = np.eye(4, dtype=np.float64)
    c2w[:3, :3] = camera.rotation.T
    c2w[:3, 3] = camera.center
    if convert_cv_to_gl:
        c2w[:3, 1:3] *= -1.0
    return c2w


def _relative_image_path(image_path: Path, scene_dir: Path) -> str:
    image_path = Path(image_path)
    try:
        return image_path.resolve().relative_to(scene_dir.resolve()).as_posix()
    except ValueError:
        return image_path.as_posix()


def generate_coarse_mesh(
    images: list[Path],
    cameras: list[Camera],
    masks: list[Array] | None = None,
    method: CoarseMeshGenerator | None = None,
) -> Mesh:
    if method is None:
        raise ValueError("A coarse mesh generator backend must be provided.")
    return method.generate(images=images, cameras=cameras, masks=masks)


def generate_coarse_mesh_from_input(
    data: ReconstructionInput,
    method: CoarseMeshGenerator,
    masks: list[Array] | None = None,
) -> Mesh:
    return generate_coarse_mesh(data.image_paths, data.cameras, masks=masks, method=method)
