from __future__ import annotations

import json
import math
import shlex
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

import numpy as np
from PIL import Image

from .data import Array, Camera, Mesh, ReconstructionInput
from .io import load_mesh, save_mesh
from .nvdiffrec import (
    NvdiffrecRunConfig,
    copy_nvdiffrec_mesh,
    find_nvdiffrec_mesh,
    prepare_nvdiffrec_run,
)
from .visibility import update_visibility


class CoarseMeshGenerator(Protocol):
    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        ...


@dataclass
class ExistingMeshGenerator:
    mesh_path: Path | str
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        mesh = load_mesh(self.mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        return mesh


@dataclass
class ExternalCommandMeshGenerator:
    command: str
    output_mesh_path: Path | str
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        subprocess.run(shlex.split(self.command), check=True)
        mesh = load_mesh(self.output_mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        return mesh


@dataclass
class NvidiaInstantNGPMeshGenerator:
    """Adapter for NVIDIA Instant-NGP-style coarse mesh generation.

    The adapter writes a NeRF-style ``transforms.json`` from this package's
    cameras, calls a user-provided command template, then imports the mesh
    generated by that command. This keeps Instant-NGP as an interchangeable
    coarse backend instead of leaking it into refinement code.
    """

    scene_dir: Path | str
    output_mesh_path: Path | str
    command_template: str
    transforms_filename: str = "transforms.json"
    aabb_scale: int = 16
    convert_cv_to_gl: bool = True
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        if not images or not cameras:
            raise ValueError("Instant-NGP backend requires image paths and cameras.")
        scene_dir = Path(self.scene_dir)
        scene_dir.mkdir(parents=True, exist_ok=True)
        transforms_path = scene_dir / self.transforms_filename
        write_instant_ngp_transforms(
            transforms_path,
            images=images,
            cameras=cameras,
            scene_dir=scene_dir,
            aabb_scale=self.aabb_scale,
            convert_cv_to_gl=self.convert_cv_to_gl,
        )

        command = self.command_template.format(
            scene_dir=str(scene_dir),
            transforms_path=str(transforms_path),
            output_mesh_path=str(self.output_mesh_path),
        )
        subprocess.run(command, shell=True, check=True)

        mesh = load_mesh(self.output_mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        mesh.attributes["coarse_backend"] = "nvidia_instant_ngp"
        mesh.attributes["instant_ngp_transforms"] = str(transforms_path)
        return mesh


@dataclass
class NvidiaNvdiffrecMeshGenerator:
    """Adapter for using NVIDIA nvdiffrec as the coarse mesh generator."""

    run_dir: Path | str
    output_mesh_path: Path | str
    nvdiffrec_root: Path | str
    command_template: str = 'python train.py --config "{config_path}"'
    result_mesh_path: Path | str | None = None
    out_name: str = "coarse"
    run_config: NvdiffrecRunConfig | None = None
    convert_cv_to_gl: bool = True
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        if not images or not cameras:
            raise ValueError("nvdiffrec backend requires image paths and cameras.")
        data = ReconstructionInput(image_paths=images, cameras=cameras, mask_paths=None)
        prepared = prepare_nvdiffrec_run(
            data,
            run_dir=self.run_dir,
            out_name=self.out_name,
            config=self.run_config,
            convert_cv_to_gl=self.convert_cv_to_gl,
            masks=masks,
        )
        command = self.command_template.format(
            config_path=str(prepared.config_path),
            dataset_dir=str(prepared.nerf_dataset_dir),
            out_dir=str(prepared.nvdiffrec_out_dir),
            output_mesh_path=str(self.output_mesh_path),
            nvdiffrec_root=str(self.nvdiffrec_root),
        )
        subprocess.run(command, shell=True, check=True, cwd=self.nvdiffrec_root)
        result_mesh = find_nvdiffrec_mesh(prepared.nvdiffrec_out_dir, self.result_mesh_path)
        copy_nvdiffrec_mesh(result_mesh, self.output_mesh_path)
        mesh = load_mesh(self.output_mesh_path).ensure_normals()
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        mesh.attributes["coarse_backend"] = "nvidia_nvdiffrec"
        mesh.attributes["nvdiffrec_config"] = str(prepared.config_path)
        mesh.attributes["nvdiffrec_output"] = str(prepared.nvdiffrec_out_dir)
        return mesh


@dataclass
class OpenMVSCommandMeshGenerator:
    """Adapter for OpenMVS-style reconstruction via a user command.

    The adapter writes either an OpenMVG-style ``sfm_data.json`` or a COLMAP
    text model from this package's cameras, calls a user-provided command
    template, then imports the mesh generated by that command.
    """

    scene_dir: Path | str
    output_mesh_path: Path | str
    command_template: str
    sfm_data_filename: str = "sfm_data.json"
    interface_format: str = "colmap"
    colmap_dirname: str = "colmap"
    copy_images: bool = True
    compute_visibility: bool = True

    def generate(
        self,
        images: list[Path],
        cameras: list[Camera],
        masks: list[Array] | None = None,
    ) -> Mesh:
        if not images or not cameras:
            raise ValueError("OpenMVS backend requires image paths and cameras.")
        scene_dir = Path(self.scene_dir)
        scene_dir.mkdir(parents=True, exist_ok=True)
        sfm_data_path = scene_dir / self.sfm_data_filename
        colmap_path = scene_dir / self.colmap_dirname
        output_mesh_path = Path(self.output_mesh_path)
        output_mesh_path.parent.mkdir(parents=True, exist_ok=True)
        if self.interface_format == "openmvg":
            write_openmvg_sfm_data(sfm_data_path, images=images, cameras=cameras, scene_dir=scene_dir)
        elif self.interface_format == "colmap":
            write_colmap_text_model(
                colmap_path,
                images=images,
                cameras=cameras,
                copy_images=self.copy_images,
            )
        else:
            raise ValueError("OpenMVS interface_format must be 'openmvg' or 'colmap'.")

        command = self.command_template.format(
            scene_dir=str(scene_dir.resolve()),
            sfm_data_path=str(sfm_data_path.resolve()),
            colmap_path=str(colmap_path.resolve()),
            colmap_sparse_path=str((colmap_path / "sparse").resolve()),
            colmap_images_path=str((colmap_path / "images").resolve()),
            output_mesh_path=str(output_mesh_path.resolve()),
        )
        command_started_at = time.time()
        subprocess.run(command, shell=True, check=True)

        mesh, result_mesh_path = load_openmvs_output_mesh(output_mesh_path, command_started_at)
        if result_mesh_path != output_mesh_path and output_mesh_path.suffix.lower() == ".obj":
            save_mesh(mesh, output_mesh_path)
        if self.compute_visibility and cameras:
            mesh.visibility = update_visibility(mesh, cameras, masks)
        mesh.attributes["coarse_backend"] = "openmvs"
        mesh.attributes["openmvs_interface_format"] = self.interface_format
        mesh.attributes["openmvs_result_mesh"] = str(result_mesh_path)
        if self.interface_format == "openmvg":
            mesh.attributes["openmvg_sfm_data"] = str(sfm_data_path)
        else:
            mesh.attributes["colmap_path"] = str(colmap_path)
        return mesh


def write_instant_ngp_transforms(
    path: Path | str,
    images: list[Path],
    cameras: list[Camera],
    scene_dir: Path | str,
    aabb_scale: int = 16,
    convert_cv_to_gl: bool = True,
) -> None:
    if len(images) != len(cameras):
        raise ValueError("Number of images and cameras must match.")
    scene_dir = Path(scene_dir)
    frames = []
    for image_path, camera in zip(images, cameras, strict=True):
        frames.append(
            {
                "file_path": _relative_image_path(image_path, scene_dir),
                "fl_x": float(camera.intrinsics[0, 0]),
                "fl_y": float(camera.intrinsics[1, 1]),
                "cx": float(camera.intrinsics[0, 2]),
                "cy": float(camera.intrinsics[1, 2]),
                "transform_matrix": camera_to_nerf_transform(
                    camera,
                    convert_cv_to_gl=convert_cv_to_gl,
                ).tolist(),
            }
        )

    first = cameras[0]
    payload = {
        "camera_model": "OPENCV",
        "fl_x": float(first.intrinsics[0, 0]),
        "fl_y": float(first.intrinsics[1, 1]),
        "cx": float(first.intrinsics[0, 2]),
        "cy": float(first.intrinsics[1, 2]),
        "w": int(first.image_size[0]) if first.image_size else None,
        "h": int(first.image_size[1]) if first.image_size else None,
        "aabb_scale": int(aabb_scale),
        "frames": frames,
    }
    if payload["w"] is None:
        del payload["w"]
        del payload["h"]

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def load_openmvs_output_mesh(output_mesh_path: Path | str, command_started_at: float | None = None) -> tuple[Mesh, Path]:
    """Load the mesh OpenMVS wrote, accounting for extension rewrites."""

    output_mesh_path = Path(output_mesh_path)
    candidates = [output_mesh_path]
    ply_path = output_mesh_path.with_suffix(".ply")
    if ply_path != output_mesh_path:
        candidates.append(ply_path)
    existing = [path for path in candidates if path.exists()]
    if command_started_at is not None:
        existing.sort(
            key=lambda path: (
                path.stat().st_mtime >= command_started_at - 1.0,
                path.stat().st_mtime,
            ),
            reverse=True,
        )
    last_error: Exception | None = None
    for candidate in existing:
        try:
            mesh = load_mesh(candidate).ensure_normals()
        except (OSError, UnicodeDecodeError, ValueError) as exc:
            last_error = exc
            continue
        if mesh.num_faces == 0:
            last_error = ValueError(f"Mesh has no faces: {candidate}")
            continue
        return mesh, candidate
    if last_error is not None:
        raise ValueError(f"No loadable OpenMVS mesh found for {output_mesh_path}") from last_error
    raise FileNotFoundError(f"No OpenMVS mesh found at {output_mesh_path} or {ply_path}")


def write_openmvg_sfm_data(
    path: Path | str,
    images: list[Path],
    cameras: list[Camera],
    scene_dir: Path | str,
) -> None:
    if len(images) != len(cameras):
        raise ValueError("Number of images and cameras must match.")
    scene_dir = Path(scene_dir)
    views: list[dict[str, object]] = []
    intrinsics: list[dict[str, object]] = []
    extrinsics: list[dict[str, object]] = []

    for idx, (image_path, camera) in enumerate(zip(images, cameras, strict=True)):
        width, height = _resolve_image_size(image_path, camera)
        view_data = {
            "local_path": "",
            "filename": _relative_image_path(image_path, scene_dir),
            "width": int(width),
            "height": int(height),
            "id_view": idx,
            "id_intrinsic": idx,
            "id_pose": idx,
        }
        views.append({"key": idx, "value": {"ptr_wrapper": {"id": 2147483649, "data": view_data}}})

        intrinsics_data = {
            "width": int(width),
            "height": int(height),
            "focal_length": float(camera.intrinsics[0, 0]),
            "principal_point": [float(camera.intrinsics[0, 2]), float(camera.intrinsics[1, 2])],
            "disto_k3": [0.0, 0.0, 0.0],
        }
        intrinsics.append(
            {
                "key": idx,
                "value": {
                    "polymorphic_name": "pinhole",
                    "ptr_wrapper": {"id": 2147483649, "data": intrinsics_data},
                },
            }
        )

        rotation = camera.rotation.reshape(-1).tolist()
        extrinsics.append({"key": idx, "value": {"rotation": rotation, "center": camera.center.tolist()}})

    payload = {
        "sfm_data_version": "0.3",
        "root_path": str(scene_dir),
        "views": views,
        "intrinsics": intrinsics,
        "extrinsics": extrinsics,
        "structure": [],
    }
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def write_colmap_text_model(
    path: Path | str,
    images: list[Path],
    cameras: list[Camera],
    copy_images: bool = True,
) -> Path:
    """Write a minimal COLMAP text model accepted by OpenMVS InterfaceCOLMAP."""

    if len(images) != len(cameras):
        raise ValueError("Number of images and cameras must match.")
    root = Path(path)
    image_dir = root / "images"
    sparse_dir = root / "sparse"
    image_dir.mkdir(parents=True, exist_ok=True)
    sparse_dir.mkdir(parents=True, exist_ok=True)

    image_names: list[str] = []
    for idx, image_path in enumerate(images, start=1):
        image_path = Path(image_path)
        suffix = image_path.suffix or ".png"
        image_name = f"{idx:08d}{suffix}"
        image_names.append(image_name)
        if copy_images:
            shutil.copy2(image_path, image_dir / image_name)

    with (sparse_dir / "cameras.txt").open("w", encoding="utf-8") as handle:
        handle.write("# Camera list with one line of data per camera:\n")
        handle.write("#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]\n")
        for idx, camera in enumerate(cameras, start=1):
            width, height = _resolve_image_size(images[idx - 1], camera)
            fx = float(camera.intrinsics[0, 0])
            fy = float(camera.intrinsics[1, 1])
            cx = float(camera.intrinsics[0, 2])
            cy = float(camera.intrinsics[1, 2])
            handle.write(f"{idx} PINHOLE {int(width)} {int(height)} {fx:.17g} {fy:.17g} {cx:.17g} {cy:.17g}\n")

    with (sparse_dir / "images.txt").open("w", encoding="utf-8") as handle:
        handle.write("# Image list with two lines of data per image:\n")
        handle.write("#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME\n")
        handle.write("#   POINTS2D[] as (X, Y, POINT3D_ID)\n")
        for idx, (camera, image_name) in enumerate(zip(cameras, image_names, strict=True), start=1):
            qw, qx, qy, qz = rotation_matrix_to_quaternion(camera.rotation)
            tx, ty, tz = camera.translation
            handle.write(
                f"{idx} {qw:.17g} {qx:.17g} {qy:.17g} {qz:.17g} "
                f"{float(tx):.17g} {float(ty):.17g} {float(tz):.17g} {idx} {image_name}\n"
            )
            handle.write("\n")

    with (sparse_dir / "points3D.txt").open("w", encoding="utf-8") as handle:
        handle.write("# 3D point list with one line of data per point:\n")
        handle.write("#   POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACK[] as (IMAGE_ID, POINT2D_IDX)\n")
        handle.write("# Number of points: 0, mean track length: 0\n")

    return root


def rotation_matrix_to_quaternion(rotation: Array) -> tuple[float, float, float, float]:
    rotation = np.asarray(rotation, dtype=np.float64)
    if rotation.shape != (3, 3):
        raise ValueError("rotation must have shape (3, 3).")
    trace = float(np.trace(rotation))
    if trace > 0.0:
        s = math.sqrt(trace + 1.0) * 2.0
        qw = 0.25 * s
        qx = (rotation[2, 1] - rotation[1, 2]) / s
        qy = (rotation[0, 2] - rotation[2, 0]) / s
        qz = (rotation[1, 0] - rotation[0, 1]) / s
    elif rotation[0, 0] > rotation[1, 1] and rotation[0, 0] > rotation[2, 2]:
        s = math.sqrt(1.0 + rotation[0, 0] - rotation[1, 1] - rotation[2, 2]) * 2.0
        qw = (rotation[2, 1] - rotation[1, 2]) / s
        qx = 0.25 * s
        qy = (rotation[0, 1] + rotation[1, 0]) / s
        qz = (rotation[0, 2] + rotation[2, 0]) / s
    elif rotation[1, 1] > rotation[2, 2]:
        s = math.sqrt(1.0 + rotation[1, 1] - rotation[0, 0] - rotation[2, 2]) * 2.0
        qw = (rotation[0, 2] - rotation[2, 0]) / s
        qx = (rotation[0, 1] + rotation[1, 0]) / s
        qy = 0.25 * s
        qz = (rotation[1, 2] + rotation[2, 1]) / s
    else:
        s = math.sqrt(1.0 + rotation[2, 2] - rotation[0, 0] - rotation[1, 1]) * 2.0
        qw = (rotation[1, 0] - rotation[0, 1]) / s
        qx = (rotation[0, 2] + rotation[2, 0]) / s
        qy = (rotation[1, 2] + rotation[2, 1]) / s
        qz = 0.25 * s
    quat = np.array([qw, qx, qy, qz], dtype=np.float64)
    quat /= max(float(np.linalg.norm(quat)), 1e-12)
    return tuple(float(x) for x in quat)


def camera_to_nerf_transform(camera: Camera, convert_cv_to_gl: bool = True) -> Array:
    c2w = np.eye(4, dtype=np.float64)
    c2w[:3, :3] = camera.rotation.T
    c2w[:3, 3] = camera.center
    if convert_cv_to_gl:
        c2w[:3, 1:3] *= -1.0
    return c2w


def _relative_image_path(image_path: Path, scene_dir: Path) -> str:
    image_path = Path(image_path)
    try:
        return image_path.resolve().relative_to(scene_dir.resolve()).as_posix()
    except ValueError:
        return image_path.as_posix()


def _resolve_image_size(image_path: Path, camera: Camera) -> tuple[int, int]:
    if camera.image_size is not None:
        return camera.image_size
    with Image.open(image_path) as img:
        return img.size


def generate_coarse_mesh(
    images: list[Path],
    cameras: list[Camera],
    masks: list[Array] | None = None,
    method: CoarseMeshGenerator | None = None,
) -> Mesh:
    if method is None:
        raise ValueError("A coarse mesh generator backend must be provided.")
    return method.generate(images=images, cameras=cameras, masks=masks)


def generate_coarse_mesh_from_input(
    data: ReconstructionInput,
    method: CoarseMeshGenerator,
    masks: list[Array] | None = None,
) -> Mesh:
    return generate_coarse_mesh(data.image_paths, data.cameras, masks=masks, method=method)
