from __future__ import annotations

from pathlib import Path

import numpy as np

from .data import Mesh


def load_mesh(path: str | Path) -> Mesh:
    path = Path(path)
    suffix = path.suffix.lower()
    if suffix == ".obj":
        return load_obj(path)
    if suffix == ".ply":
        return load_ascii_ply(path)
    raise ValueError(f"Unsupported mesh format: {path.suffix}")


def save_mesh(mesh: Mesh, path: str | Path) -> None:
    path = Path(path)
    suffix = path.suffix.lower()
    if suffix != ".obj":
        raise ValueError("Only OBJ export is currently supported.")
    save_obj(mesh, path)


def load_obj(path: Path) -> Mesh:
    vertices: list[list[float]] = []
    normals: list[list[float]] = []
    faces: list[list[int]] = []
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if parts[0] == "v":
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == "vn":
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif parts[0] == "f":
                face = []
                for item in parts[1:4]:
                    vertex_token = item.split("/")[0]
                    face.append(int(vertex_token) - 1)
                faces.append(face)
    mesh = Mesh(np.asarray(vertices), np.asarray(faces, dtype=np.int64))
    if len(normals) == mesh.num_vertices:
        mesh.normals = np.asarray(normals, dtype=np.float64)
    else:
        mesh.ensure_normals()
    return mesh


def save_obj(mesh: Mesh, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mesh.ensure_normals()
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Generated by multiview-laplacian-refinement\n")
        for vertex in mesh.vertices:
            handle.write(f"v {vertex[0]:.9g} {vertex[1]:.9g} {vertex[2]:.9g}\n")
        if mesh.normals is not None:
            for normal in mesh.normals:
                handle.write(f"vn {normal[0]:.9g} {normal[1]:.9g} {normal[2]:.9g}\n")
        for face in mesh.faces:
            if mesh.normals is not None:
                a, b, c = face + 1
                handle.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")
            else:
                handle.write(f"f {face[0] + 1} {face[1] + 1} {face[2] + 1}\n")


def load_ascii_ply(path: Path) -> Mesh:
    with path.open("r", encoding="utf-8") as handle:
        if handle.readline().strip() != "ply":
            raise ValueError("Only ASCII PLY files are supported.")
        vertex_count = None
        face_count = None
        while True:
            line = handle.readline()
            if not line:
                raise ValueError("Unexpected end of PLY header.")
            line = line.strip()
            if line.startswith("format") and "ascii" not in line:
                raise ValueError("Only ASCII PLY files are supported.")
            if line.startswith("element vertex"):
                vertex_count = int(line.split()[-1])
            elif line.startswith("element face"):
                face_count = int(line.split()[-1])
            elif line == "end_header":
                break
        if vertex_count is None or face_count is None:
            raise ValueError("PLY header must declare vertex and face counts.")
        vertices = []
        for _ in range(vertex_count):
            parts = handle.readline().split()
            vertices.append([float(parts[0]), float(parts[1]), float(parts[2])])
        faces = []
        for _ in range(face_count):
            parts = handle.readline().split()
            count = int(parts[0])
            if count != 3:
                continue
            faces.append([int(parts[1]), int(parts[2]), int(parts[3])])
    return Mesh(np.asarray(vertices), np.asarray(faces, dtype=np.int64)).ensure_normals()
